// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiMS-cPywdTuhn6AND4jAgp-7SMl3gOSw',
    appId: '1:406734213584:web:3d9a48bc6d4d626f3669d5',
    messagingSenderId: '406734213584',
    projectId: 'monitoringpasien-2ace2',
    authDomain: 'monitoringpasien-2ace2.firebaseapp.com',
    databaseURL: 'https://monitoringpasien-2ace2-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringpasien-2ace2.firebasestorage.app',
    measurementId: 'G-WKRHE7SE12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7VMiU9IXhTn_zGq607Yo5XFkAyAdJZ7s',
    appId: '1:406734213584:android:6380c234f57e14413669d5',
    messagingSenderId: '406734213584',
    projectId: 'monitoringpasien-2ace2',
    databaseURL: 'https://monitoringpasien-2ace2-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringpasien-2ace2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7M8GrUJX4uAdh63cyVOrKuP03WqDoJCY',
    appId: '1:406734213584:ios:436c39fa47cc3be03669d5',
    messagingSenderId: '406734213584',
    projectId: 'monitoringpasien-2ace2',
    databaseURL: 'https://monitoringpasien-2ace2-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringpasien-2ace2.firebasestorage.app',
    iosBundleId: 'com.example.flutterMonitoringPasien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7M8GrUJX4uAdh63cyVOrKuP03WqDoJCY',
    appId: '1:406734213584:ios:436c39fa47cc3be03669d5',
    messagingSenderId: '406734213584',
    projectId: 'monitoringpasien-2ace2',
    databaseURL: 'https://monitoringpasien-2ace2-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringpasien-2ace2.firebasestorage.app',
    iosBundleId: 'com.example.flutterMonitoringPasien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiMS-cPywdTuhn6AND4jAgp-7SMl3gOSw',
    appId: '1:406734213584:web:ca2ac3c59fbdc3973669d5',
    messagingSenderId: '406734213584',
    projectId: 'monitoringpasien-2ace2',
    authDomain: 'monitoringpasien-2ace2.firebaseapp.com',
    databaseURL: 'https://monitoringpasien-2ace2-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringpasien-2ace2.firebasestorage.app',
    measurementId: 'G-2Q401GTQXB',
  );
}
